### ISSUE TITLE
Peer-to-peer code review - week 4 - friday

### ISSUE THREAD

**Issue by gtekle** [joskalenda/portfolio#10]
You have done a great job in addressing the tasks requirements! well done!
However, we have few suggestion that we believe will improve your code further.
1. [optional] The email validation can be done using regular expressions.
2. we suggest that the `css` styles for the error message div can be put inside the `css` file.

**Comment by joskalenda** [comment]
Hi there!
Thank you all for addressing this issue, your remarks are very meaningful to me and I am going to perform them.
